# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - docs/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '10.x'
  publishFolder: 'dist'
  codeCoverageFile: 'coverage/cobertura-coverage.xml'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(nodeVersion)'
    displayName: 'Setup Environment'

  - script: |
      yarn
      yarn build
    displayName: 'Build'

   - script: |
      yarn test
      yarn test:coverage
    displayName: 'Test'

  - template: templates/build.yml
    parameters:
      buildConfig: 'Debug'
    displayName: 'Put Info'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(codeCoverageFile)
    displayName: Publish Test Coverage

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(publishFolder)'
    displayName: 'Publish Build'
